[package]
name = "abc163"
version = "0.1.0"
edition = "2018"
# lto = true
# panic = 'abort'

# dependencies added to new project
[dependencies]
num = "=0.2.1"
proconio = { version = "=0.3.6", features = ["derive"] }
superslice = "=1.0.0"

[profile.release]
