[package]
name = "tessoku-book"
version = "0.1.0"
edition = "2018"

# dependencies added to new project
[dependencies]
num = "=0.2.1"
proconio = { version = "=0.3.6", features = ["derive"] }
rand = "=0.7.3"
superslice = "=1.0.0"

